### ISSUE TITLE
What type of GeoJSON file can convert to geoparquet?

### ISSUE THREAD

**Issue by onsummer** [tschaub/gpq#23]
Here is my little GeoJSON file:

```json
{
  "type": "FeatureCollection",
  "name": "demo",
  "crs": {
    "type": "name",
    "properties": {
      "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
    }
  },
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              110.189014185542902,
              22.656808012935379
            ],
            [
              110.203307696738648,
              22.668788827097494
            ],
            [
              110.213968273838759,
              22.658264452155809
            ],
            [
              110.195595156322597,
              22.65188898133686
            ],
            [
              110.195595156322597,
              22.65188898133686
            ],
            [
              110.189014185542902,
              22.656808012935379
            ]
          ]
        ]
      }
    }
  ]
}
```

Named it `demo.geojson`, and I use gpq executable binary file to convert it:

![image](https://user-images.githubusercontent.com/26168955/208676694-8cdeffbf-6cfe-40f6-bad4-159e39213779.png)

What is the problem?

gpq version: 0.6.0

**Comment by tschaub** [comment]
@onsummer - Thanks for the report.  The program aims to parse any valid GeoJSON, and it certainly should work with the example you provide above.  A bug in the parser was getting tripped up on the nested "type" property in the "crs" object.  The 0.6.1 release includes a fix for this.

Let me know if you encounter any other unexpected behavior.
